// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGhxagXCQfWbs-Fv9Sfm7bY99RpAotUk',
    appId: '1:297664711333:web:5abda507bbe1e23b431b4c',
    messagingSenderId: '297664711333',
    projectId: 'notes-a378b',
    authDomain: 'notes-a378b.firebaseapp.com',
    databaseURL: 'https://notes-a378b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a378b.appspot.com',
    measurementId: 'G-CL28KW19V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9nvtlOmAgfjHgK-Mkq28OwmcZ4UGnDg8',
    appId: '1:297664711333:android:3c13a538d1237acb431b4c',
    messagingSenderId: '297664711333',
    projectId: 'notes-a378b',
    databaseURL: 'https://notes-a378b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a378b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7QMNtJq5gJyNcpD0_r-YDcK3cqg4nUQ',
    appId: '1:297664711333:ios:7bfef32435dd2e7a431b4c',
    messagingSenderId: '297664711333',
    projectId: 'notes-a378b',
    databaseURL: 'https://notes-a378b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a378b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7QMNtJq5gJyNcpD0_r-YDcK3cqg4nUQ',
    appId: '1:297664711333:ios:7bfef32435dd2e7a431b4c',
    messagingSenderId: '297664711333',
    projectId: 'notes-a378b',
    databaseURL: 'https://notes-a378b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a378b.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGhxagXCQfWbs-Fv9Sfm7bY99RpAotUk',
    appId: '1:297664711333:web:38e9e92ccdfa3dbf431b4c',
    messagingSenderId: '297664711333',
    projectId: 'notes-a378b',
    authDomain: 'notes-a378b.firebaseapp.com',
    databaseURL: 'https://notes-a378b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-a378b.appspot.com',
    measurementId: 'G-4VB55W04TX',
  );
}
